### ISSUE TITLE
Add changelog section to readme.txt

### ISSUE THREAD

**Issue by Zodiac1978** [jelleroorda/social-divi#4]
It would be awesome if there is a changelog section in the readme.txt to know what changed in a new version.

**Comment by Zodiac1978** [comment]
For WordPress.org the section would be more important. If you click on the details link the popup opened is the development tab of the plugin page and this is showing the changelog section (so that you can quickly check what changed). At the moment this is empty.

But yes, changelog.md is great too ;)

**Comment by lsthompson** [comment]
For sure, there are tools for that to make it even simpler:
- https://generatewp.com/plugin-readme/
- https://wordpress.org/plugins/developers/readme-validator/

Docs: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

**Comment by jelleroorda** [comment]
There's actually already a [CHANGELOG.md](https://github.com/jelleroorda/social-divi/blob/master/CHANGELOG.md) file.

**Comment by lsthompson** [comment]
It doesn't get better than that!

**Comment by Zodiac1978** [comment]
> For WordPress.org the section would be more important. If you click on the details link the popup opened is the development tab of the plugin page and this is showing the changelog section (so that you can quickly check what changed). At the moment this is empty.

https://wordpress.org/plugins/social-divi/#developers
